// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

require('./Skills.css')
;

var component = ReasonReact.reducerComponent("Skills");

function decodeSkill(json) {
  return /* record */[
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* logoName */Json_decode.field("logoName", Json_decode.string, json),
          /* star */Json_decode.field("star", Json_decode.bool, json)
        ];
}

function decodeSkills(json) {
  return /* record */[
          /* languages */Json_decode.field("languages", (function (param) {
                  return Json_decode.list(decodeSkill, param);
                }), json),
          /* frameworks */Json_decode.field("frameworks", (function (param) {
                  return Json_decode.list(decodeSkill, param);
                }), json),
          /* whatDescription */Json_decode.field("whatDescription", Json_decode.string, json)
        ];
}

function decodeSkillsData(json) {
  return /* record */[/* data */Json_decode.field("data", decodeSkills, json)];
}

var Decode = /* module */[
  /* decodeSkill */decodeSkill,
  /* decodeSkills */decodeSkills,
  /* decodeSkillsData */decodeSkillsData
];

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              return Curry._1(self[/* send */3], /* FetchSkills */0);
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "Menu"
                        }, React.createElement("div", {
                              className: "Menu-links"
                            }, React.createElement("a", {
                                  className: "Menu-link",
                                  href: "https://www.zacharywagner.net"
                                }, "Home"), React.createElement("a", {
                                  className: "Menu-link",
                                  href: "https://www.zacharywagner.net/resume"
                                }, "Resume"), React.createElement("div", {
                                  className: "Menu-link-divider-block"
                                }, React.createElement("div", {
                                      className: "Menu-link-divider"
                                    }, React.createElement("span", undefined, "Other Versions"))), React.createElement("a", {
                                  className: "Menu-link",
                                  href: "https://www.zacharywagner.net"
                                }, "React"), React.createElement("a", {
                                  className: "Menu-link",
                                  href: "https://vue.zacharywagner.net"
                                }, "Vue")));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* languages : [] */0,
                      /* frameworks : [] */0,
                      /* whatDescription */"",
                      /* isLoading */true,
                      /* hasErrored */false
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                if (action !== 0) {
                  return /* Update */Block.__(0, [/* record */[
                              /* languages */state[/* languages */0],
                              /* frameworks */state[/* frameworks */1],
                              /* whatDescription */state[/* whatDescription */2],
                              /* isLoading */false,
                              /* hasErrored */true
                            ]]);
                } else {
                  return /* UpdateWithSideEffects */Block.__(2, [
                            /* record */[
                              /* languages */state[/* languages */0],
                              /* frameworks */state[/* frameworks */1],
                              /* whatDescription */state[/* whatDescription */2],
                              /* isLoading */true,
                              /* hasErrored */false
                            ],
                            (function (self) {
                                fetch("https://www.zacharywagner.net/api/v1/skills").then((function (prim) {
                                            return prim.json();
                                          })).then((function (json) {
                                          return Promise.resolve((console.log(decodeSkillsData(json)), /* () */0));
                                        })).catch((function (_err) {
                                        return Promise.resolve(Curry._1(self[/* send */3], /* FetchSkillsErrored */1));
                                      }));
                                return /* () */0;
                              })
                          ]);
                }
              } else {
                var skillData = action[0];
                return /* Update */Block.__(0, [/* record */[
                            /* languages */skillData[/* languages */0],
                            /* frameworks */skillData[/* frameworks */1],
                            /* whatDescription */skillData[/* whatDescription */2],
                            /* isLoading */false,
                            /* hasErrored */false
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.Decode = Decode;
exports.make = make;
/*  Not a pure module */
