// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

require('./SkillTile.css')
;

var component = ReasonReact.statelessComponent("SkillTile");

function make(name, logo, star, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "SkillTile"
                        }, React.createElement("div", {
                              className: "SkillTile-label"
                            }, React.createElement("div", {
                                  className: "SkillTile-text"
                                }, name, star ? "Star" : null)), React.createElement("div", {
                              className: "SkillTile-image-block"
                            }, React.createElement("div", {
                                  className: "SkillTile-image-cell"
                                }, React.createElement("img", {
                                      className: "SkillTile-image",
                                      alt: name,
                                      src: "./assets/logos/" + ($$String.sub(logo, 0, logo.length - 4 | 0) + ".png")
                                    }))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/*  Not a pure module */
