// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var App$Whatever = require("./App.bs.js");

require('./main.css')
;

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$Whatever.make(/* array */[])), "app");

/*  Not a pure module */
