// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var PersonalSiteData = require("personal-site-data");
var FontAwesomeIcon$ReasonProfile = require("../../common/font-awesome/FontAwesomeIcon.bs.js");

require('./ProfileInfo.css')
;

var component = ReasonReact.statelessComponent("ProfileInfo");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: "ProfileInfo"
                        }, React.createElement("div", {
                              className: "ProfileInfo-inner"
                            }, React.createElement("div", {
                                  className: "ProfileInfo-inner-cell"
                                }, React.createElement("div", {
                                      className: "ProfileInfo-pic-container"
                                    }, React.createElement("img", {
                                          className: "ProfileInfo-pic-img",
                                          alt: "Zachary Wagner Profile",
                                          src: PersonalSiteData.profileImage
                                        })), React.createElement("h1", undefined, "Hey, I'm Zach,"), React.createElement("h4", {
                                      className: "ProfileInfo-h4"
                                    }, "a Front End Engineer"), React.createElement("h4", {
                                      className: "ProfileInfo-h4"
                                    }, "working in Chicago"), React.createElement("h4", {
                                      className: "ProfileInfo-h4"
                                    }, "for SpotHero"), React.createElement("div", {
                                      className: "ProfileInfo-social-icons"
                                    }, React.createElement("a", {
                                          className: "ProfileInfo-social-link ProfileInfo-linkedin-link",
                                          href: "https://www.linkedin.com/in/zacharywagner",
                                          rel: "noopener noreferrer",
                                          target: "_blank"
                                        }, ReasonReact.element(undefined, undefined, FontAwesomeIcon$ReasonProfile.make(/* :: */[
                                                  "fab",
                                                  /* :: */[
                                                    "linkedin",
                                                    /* [] */0
                                                  ]
                                                ], undefined, "ProfileInfo-social-icon", undefined, "2x", true, /* array */[]))), React.createElement("a", {
                                          className: "ProfileInfo-social-link ProfileInfo-github-link",
                                          href: "https://github.com/zwagner86",
                                          rel: "noopener noreferrer",
                                          target: "_blank"
                                        }, ReasonReact.element(undefined, undefined, FontAwesomeIcon$ReasonProfile.make(/* :: */[
                                                  "fab",
                                                  /* :: */[
                                                    "github",
                                                    /* [] */0
                                                  ]
                                                ], undefined, "ProfileInfo-social-icon", undefined, "2x", true, /* array */[])))), React.createElement("div", {
                                      className: "ProfileInfo-resume-link"
                                    }, React.createElement("a", {
                                          className: "ProfileInfo-resume-btn",
                                          href: "https://www.zacharywagner.net/resume"
                                        }, "View Resume")))));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/*  Not a pure module */
